// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/community": {
    params: {};
  };
  "/test-styles": {
    params: {};
  };
  "/venues": {
    params: {};
  };
  "/venues/:slug": {
    params: {
      "slug": string;
    };
  };
  "/venues/new": {
    params: {};
  };
  "/venues/:slug/edit": {
    params: {
      "slug": string;
    };
  };
  "/resources": {
    params: {};
  };
  "/resources/band-history": {
    params: {};
  };
  "/resources/chemical-warfare-brigade": {
    params: {};
  };
  "/resources/hot-air-balloon": {
    params: {};
  };
  "/resources/media": {
    params: {};
  };
  "/resources/mixes": {
    params: {};
  };
  "/resources/movie-scores": {
    params: {};
  };
  "/resources/music": {
    params: {};
  };
  "/resources/perfume": {
    params: {};
  };
  "/resources/side-projects": {
    params: {};
  };
  "/resources/think-tank": {
    params: {};
  };
  "/resources/tractorbeam": {
    params: {};
  };
  "/resources/touchdowns": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/auth/forgot-password": {
    params: {};
  };
  "/profile/edit": {
    params: {};
  };
  "/users/:username": {
    params: {
      "username": string;
    };
  };
  "/blog": {
    params: {};
  };
  "/blog/new": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/blog/:slug/edit": {
    params: {
      "slug": string;
    };
  };
  "/shows": {
    params: {};
  };
  "/shows/:slug": {
    params: {
      "slug": string;
    };
  };
  "/shows/top-rated": {
    params: {};
  };
  "/shows/tour-dates": {
    params: {};
  };
  "/shows/new": {
    params: {};
  };
  "/shows/:slug/edit": {
    params: {
      "slug": string;
    };
  };
  "/songs": {
    params: {};
  };
  "/songs/:slug": {
    params: {
      "slug": string;
    };
  };
  "/songs/new": {
    params: {};
  };
  "/songs/:slug/edit": {
    params: {
      "slug": string;
    };
  };
  "/api/reviews": {
    params: {};
  };
  "/api/ratings": {
    params: {};
  };
  "/api/attendances": {
    params: {};
  };
  "/api/venues": {
    params: {};
  };
  "/api/songs": {
    params: {};
  };
  "/api/tracks": {
    params: {};
  };
  "/api/tracks/reorder": {
    params: {};
  };
  "/api/tracks/:id": {
    params: {
      "id": string;
    };
  };
  "/api/search": {
    params: {};
  };
  "/api/users": {
    params: {};
  };
  "/api/contact": {
    params: {};
  };
  "/api/cron/:action": {
    params: {
      "action": string;
    };
  };
  "/healthcheck": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/terms" | "/privacy" | "/community" | "/test-styles" | "/venues" | "/venues/:slug" | "/venues/new" | "/venues/:slug/edit" | "/resources" | "/resources/band-history" | "/resources/chemical-warfare-brigade" | "/resources/hot-air-balloon" | "/resources/media" | "/resources/mixes" | "/resources/movie-scores" | "/resources/music" | "/resources/perfume" | "/resources/side-projects" | "/resources/think-tank" | "/resources/tractorbeam" | "/resources/touchdowns" | "/auth/login" | "/auth/register" | "/auth/callback" | "/auth/logout" | "/auth/forgot-password" | "/profile/edit" | "/users/:username" | "/blog" | "/blog/new" | "/blog/:slug" | "/blog/:slug/edit" | "/shows" | "/shows/:slug" | "/shows/top-rated" | "/shows/tour-dates" | "/shows/new" | "/shows/:slug/edit" | "/songs" | "/songs/:slug" | "/songs/new" | "/songs/:slug/edit" | "/api/reviews" | "/api/ratings" | "/api/attendances" | "/api/venues" | "/api/songs" | "/api/tracks" | "/api/tracks/reorder" | "/api/tracks/:id" | "/api/search" | "/api/users" | "/api/contact" | "/api/cron/:action" | "/healthcheck";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/community.tsx": {
    id: "routes/community";
    page: "/community";
  };
  "routes/test-styles.tsx": {
    id: "routes/test-styles";
    page: "/test-styles";
  };
  "routes/venues/_layout.tsx": {
    id: "routes/venues/_layout";
    page: "/venues" | "/venues/:slug" | "/venues/new" | "/venues/:slug/edit";
  };
  "routes/venues/index.tsx": {
    id: "routes/venues/index";
    page: "/venues";
  };
  "routes/venues/$slug.tsx": {
    id: "routes/venues/$slug";
    page: "/venues/:slug";
  };
  "routes/venues/new.tsx": {
    id: "routes/venues/new";
    page: "/venues/new";
  };
  "routes/venues/$slug.edit.tsx": {
    id: "routes/venues/$slug.edit";
    page: "/venues/:slug/edit";
  };
  "routes/resources/_layout.tsx": {
    id: "routes/resources/_layout";
    page: "/resources" | "/resources/band-history" | "/resources/chemical-warfare-brigade" | "/resources/hot-air-balloon" | "/resources/media" | "/resources/mixes" | "/resources/movie-scores" | "/resources/music" | "/resources/perfume" | "/resources/side-projects" | "/resources/think-tank" | "/resources/tractorbeam" | "/resources/touchdowns";
  };
  "routes/resources/_index.tsx": {
    id: "routes/resources/_index";
    page: "/resources";
  };
  "routes/resources/band-history.tsx": {
    id: "routes/resources/band-history";
    page: "/resources/band-history";
  };
  "routes/resources/chemical-warfare-brigade.tsx": {
    id: "routes/resources/chemical-warfare-brigade";
    page: "/resources/chemical-warfare-brigade";
  };
  "routes/resources/hot-air-balloon.tsx": {
    id: "routes/resources/hot-air-balloon";
    page: "/resources/hot-air-balloon";
  };
  "routes/resources/media.tsx": {
    id: "routes/resources/media";
    page: "/resources/media";
  };
  "routes/resources/mixes.tsx": {
    id: "routes/resources/mixes";
    page: "/resources/mixes";
  };
  "routes/resources/movie-scores.tsx": {
    id: "routes/resources/movie-scores";
    page: "/resources/movie-scores";
  };
  "routes/resources/music.tsx": {
    id: "routes/resources/music";
    page: "/resources/music";
  };
  "routes/resources/perfume.tsx": {
    id: "routes/resources/perfume";
    page: "/resources/perfume";
  };
  "routes/resources/side-projects.tsx": {
    id: "routes/resources/side-projects";
    page: "/resources/side-projects";
  };
  "routes/resources/think-tank.tsx": {
    id: "routes/resources/think-tank";
    page: "/resources/think-tank";
  };
  "routes/resources/tractorbeam.tsx": {
    id: "routes/resources/tractorbeam";
    page: "/resources/tractorbeam";
  };
  "routes/resources/touchdowns.tsx": {
    id: "routes/resources/touchdowns";
    page: "/resources/touchdowns";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/auth/login";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/auth/register";
  };
  "routes/auth/callback.tsx": {
    id: "routes/auth/callback";
    page: "/auth/callback";
  };
  "routes/auth/logout.tsx": {
    id: "routes/auth/logout";
    page: "/auth/logout";
  };
  "routes/auth/forgot-password.tsx": {
    id: "routes/auth/forgot-password";
    page: "/auth/forgot-password";
  };
  "routes/profile/edit.tsx": {
    id: "routes/profile/edit";
    page: "/profile/edit";
  };
  "routes/users/$username.tsx": {
    id: "routes/users/$username";
    page: "/users/:username";
  };
  "routes/blog/_layout.tsx": {
    id: "routes/blog/_layout";
    page: "/blog" | "/blog/new" | "/blog/:slug" | "/blog/:slug/edit";
  };
  "routes/blog/_index.tsx": {
    id: "routes/blog/_index";
    page: "/blog";
  };
  "routes/blog/new.tsx": {
    id: "routes/blog/new";
    page: "/blog/new";
  };
  "routes/blog/$slug.tsx": {
    id: "routes/blog/$slug";
    page: "/blog/:slug";
  };
  "routes/blog/$slug.edit.tsx": {
    id: "routes/blog/$slug.edit";
    page: "/blog/:slug/edit";
  };
  "routes/shows/_layout.tsx": {
    id: "routes/shows/_layout";
    page: "/shows" | "/shows/:slug" | "/shows/top-rated" | "/shows/tour-dates" | "/shows/new" | "/shows/:slug/edit";
  };
  "routes/shows/_index.tsx": {
    id: "routes/shows/_index";
    page: "/shows";
  };
  "routes/shows/$slug.tsx": {
    id: "routes/shows/$slug";
    page: "/shows/:slug";
  };
  "routes/shows/top-rated.tsx": {
    id: "routes/shows/top-rated";
    page: "/shows/top-rated";
  };
  "routes/shows/tour-dates.tsx": {
    id: "routes/shows/tour-dates";
    page: "/shows/tour-dates";
  };
  "routes/shows/new.tsx": {
    id: "routes/shows/new";
    page: "/shows/new";
  };
  "routes/shows/$slug.edit.tsx": {
    id: "routes/shows/$slug.edit";
    page: "/shows/:slug/edit";
  };
  "routes/songs/_layout.tsx": {
    id: "routes/songs/_layout";
    page: "/songs" | "/songs/:slug" | "/songs/new" | "/songs/:slug/edit";
  };
  "routes/songs/_index.tsx": {
    id: "routes/songs/_index";
    page: "/songs";
  };
  "routes/songs/$slug.tsx": {
    id: "routes/songs/$slug";
    page: "/songs/:slug";
  };
  "routes/songs/new.tsx": {
    id: "routes/songs/new";
    page: "/songs/new";
  };
  "routes/songs/$slug.edit.tsx": {
    id: "routes/songs/$slug.edit";
    page: "/songs/:slug/edit";
  };
  "routes/api/reviews.tsx": {
    id: "routes/api/reviews";
    page: "/api/reviews";
  };
  "routes/api/ratings.tsx": {
    id: "routes/api/ratings";
    page: "/api/ratings";
  };
  "routes/api/attendances.tsx": {
    id: "routes/api/attendances";
    page: "/api/attendances";
  };
  "routes/api/venues.tsx": {
    id: "routes/api/venues";
    page: "/api/venues";
  };
  "routes/api/songs.tsx": {
    id: "routes/api/songs";
    page: "/api/songs";
  };
  "routes/api/tracks.tsx": {
    id: "routes/api/tracks";
    page: "/api/tracks";
  };
  "routes/api/tracks/reorder.tsx": {
    id: "routes/api/tracks/reorder";
    page: "/api/tracks/reorder";
  };
  "routes/api/tracks/$id.tsx": {
    id: "routes/api/tracks/$id";
    page: "/api/tracks/:id";
  };
  "routes/api/search.tsx": {
    id: "routes/api/search";
    page: "/api/search";
  };
  "routes/api/users.tsx": {
    id: "routes/api/users";
    page: "/api/users";
  };
  "routes/api/contact.tsx": {
    id: "routes/api/contact";
    page: "/api/contact";
  };
  "routes/api/cron/$action.tsx": {
    id: "routes/api/cron/$action";
    page: "/api/cron/:action";
  };
  "routes/healthcheck.tsx": {
    id: "routes/healthcheck";
    page: "/healthcheck";
  };
};